// frontend/src/pages/Register.tsx
import React from "react";
import { Redirect } from "react-router-dom";
import axios from "axios";
import Input from "../components/Input";
import Button from "../components/Button";

type Token = {
  token: string;
};

const Register = () => {
  const [status, setStatus] = React.useState(false);
  const [username, setUsername] = React.useState("");
  const [email, setEmail] = React.useState("");
  const [password, setPassword] = React.useState("");
  const [confirm, setConfirm] = React.useState("");

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (confirm !== password) {
      alert("Passwords do not match");
      return;
    }

    const url = "http://localhost:3001/auth/register";
    const payload = {
      email: email,
      username: username,
      password: password,
    };

    axios
      .post<Token>(url, payload)
      .then((response) => {
        console.log(response);
        localStorage.setItem("user", response.data.token);
        return setStatus(true);
      })
      .catch((err: Error) => {
        console.error(err);
      });
  };

  if (status || localStorage.getItem("user")) {
    return <Redirect to="/" />;
  }

  return (
    <React.Fragment>
      <form onSubmit={handleSubmit}>
        <h3>Register</h3>
        <Input
          type="text"
          label="Username"
          placeholder="Username"
          onChange={({ target }) => {
            setUsername(target.value);
          }}
        />
        <Input
          type="text"
          label="Email"
          placeholder="Email"
          onChange={({ target }) => {
            setEmail(target.value);
          }}
        />
        <Input
          type="password"
          label="Password"
          placeholder="Enter your password"
          onChange={({ target }) => {
            setPassword(target.value);
          }}
        />
        <Input
          type="password"
          label="Confirm Password"
          placeholder="Confirm your password"
          onChange={({ target }) => {
            setConfirm(target.value);
          }}
        />
        <Button type="submit" title="Register" />
      </form>
    </React.Fragment>
  );
};

export default Register;

// frontend/src/views/Register.vue
<template>
  <div>
    <h1>Register Page</h1>
    <form @submit.prevent>
      <my-input v-model="username" type="text" placeholder="Username" />
      <my-input v-model="email" type="text" placeholder="Email" />
      <my-input v-model="password" type="password" placeholder="Password" />
      <my-input
        v-model="confirmPassword"
        type="password"
        placeholder="Confirm Password"
      />
      <my-button @click="register">Register</my-button>
    </form>
  </div>
</template>

<script>
import MyInput from "../components/UI/MyInput";
import MyButton from "../components/UI/MyButton";
import axios from "axios";
export default {
  components: { MyButton, MyInput },
  data() {
    return {
      username: "",
      password: "",
      email: "",
      confirmPassword: "",
    };
  },
  methods: {
    async register() {
      if (this.password !== this.confirmPassword) {
        alert("Passwords do not match");
        return;
      } else if (
        this.password.trim() === "" ||
        this.email.trim() === "" ||
        this.username.trim() === ""
      ) {
        alert("Fill the Fields");
        return;
      } else if (
        /^\w+([-]?\w+)*@\w+([-]?\w+)*(\.\w{2,3})+$/.test(this.email) === false
      ) {
        alert(`${this.email} is not an email`);
        return;
      }
      try {
        const resp = await axios.post("http://localhost:3001/auth/register", {
          username: this.username,
          email: this.email,
          password: this.password,
        });

        localStorage.setItem("user", resp.data.accessToken);
        this.username = "";
        this.password = "";
        this.email = "";
        this.$store.commit("setAuth");
        await this.$router.push("/");
      } catch (e) {
        this.username = "";
        this.email = "";
        this.password = "";
        alert("User with this username or email already exists");
      }
    },
  },
  beforeMount() {
    if (localStorage.getItem("user")) {
      this.$router.push("/");
    }
  },
};
</script>

<style scoped></style>
